---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86185.
--- DateTime: 2021/7/11 21:26
---

N = 8 -- board size

-- checks whether position (n,c) is free from attack

local function is_place_ok(a, n, c)
    --io.write("check n : "..n..", check c : "..c.."\n")
    for i = 1, n - 1 do -- for each previously place queen
        if (a[i] == c) or
           (a[i] - i == c - n) or
           (a[i] + i == c + n) then
            return false
        end
    end
    return true;
end

-- print a board
local function print_solution (a)
    for i = 1, N do -- for each row
        for j = 1, N do -- for each column
            io.write(a[i] == j and "X" or "-", " ")
        end
        io.write("\n")
    end
    io.write("\n")
end

-- add queen
function add_queen(a, n)
    if n > N then
        print_solution(a)
    else
        for c = 1, N do
            if is_place_ok(a, n, c) then
                a[n] = c
                add_queen(a, n+1)
            end
        end
    end
end

-- run the program

add_queen({}, 1)
